/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conversor;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author walterquijada
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué desea realizar?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Convertir monedas", "Convertir Temperaturas" }));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String o = (String) jComboBox1.getSelectedItem();
        if (o == "Convertir monedas") {
            conversor_moneda j = new conversor_moneda();
            j.setDefaultCloseOperation(conversor_moneda.EXIT_ON_CLOSE);
            this.setVisible(false);
            j.setVisible(true);
            j.pack();
            j.setTitle("Conversor de monedas");
            j.setLocationRelativeTo(null);
            j.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent we) {
                    int result = JOptionPane.showConfirmDialog(j,
                            "¿Desea salir?", "Cerrar ",
                            JOptionPane.YES_NO_OPTION);
                    if (result == JOptionPane.YES_OPTION) {
                        j.setDefaultCloseOperation(j.EXIT_ON_CLOSE);
                    } else if (result == JOptionPane.NO_OPTION) {
                        j.setDefaultCloseOperation(j.DO_NOTHING_ON_CLOSE);
                    }
                }
            });
        } else {
            temperaturas j = new temperaturas();
            j.setDefaultCloseOperation(temperaturas.EXIT_ON_CLOSE);
            this.setVisible(false);
            j.setVisible(true);
            j.pack();
            j.setTitle("Conversor de temperaturas");
            j.setLocationRelativeTo(null);
            j.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent we) {

                    int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?",
                            "Cerrar", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE, null);
                    if (result == JOptionPane.YES_OPTION) {
                        j.setDefaultCloseOperation(j.EXIT_ON_CLOSE);
                    } else if (result == JOptionPane.NO_OPTION) {
                        j.setDefaultCloseOperation(j.DO_NOTHING_ON_CLOSE);
                    }
                }
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App j = new App();
                j.setDefaultCloseOperation(App.EXIT_ON_CLOSE);
                j.setTitle("Bienvenido");
                j.setLocationRelativeTo(null);
                j.setVisible(true);

                /**
                 *
                 */
                j.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent we) {
                        int result = JOptionPane.showConfirmDialog(j,
                                "¿Desea salir?", "Cerrar ",
                                JOptionPane.YES_NO_OPTION);
                        if (result == JOptionPane.YES_OPTION) {
                            j.setDefaultCloseOperation(j.EXIT_ON_CLOSE);
                        } else if (result == JOptionPane.NO_OPTION) {
                            j.setDefaultCloseOperation(j.DO_NOTHING_ON_CLOSE);
                        }
                    }
                });
                /**
                 *
                 */

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
