/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conversor;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author walterquijada
 */
public class conversor_moneda extends javax.swing.JFrame {

    /**
     * Creates new form conversor_moneda
     */
    public conversor_moneda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese cantidad:");

        jLabel2.setText("Convertir de:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar", "Euros", "Pesos Mexicanos", "Libra Esterlina", "Quetzales", "Yen Japonés", "Won sul-coreano" }));

        jLabel3.setText("Convertir a:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar", "Euros", "Pesos Mexicanos", "Libra Esterlina", "Quetzales", "Yen Japonés", "Won sul-coreano" }));

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Regresar al inicio");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 188, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        App n = new App();
        n.setVisible(true);
        n.setTitle("Bienvenido");
        n.setLocationRelativeTo(null);
        n.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent we) {
                    int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?",
                            "Cerrar", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE, null);
                    if (result == JOptionPane.YES_OPTION) {
                        n.setDefaultCloseOperation(n.EXIT_ON_CLOSE);
                    } else if (result == JOptionPane.NO_OPTION) {
                        n.setDefaultCloseOperation(n.DO_NOTHING_ON_CLOSE);
                    }
                }
            });
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto = jTextField1.getText();
        String o = (String) jComboBox1.getSelectedItem();
        String d = (String) jComboBox2.getSelectedItem();
        double m = 0.0;
        if(!texto.equals("")){
        boolean isNumeric = (texto != null && texto.matches("^[0-9]+([.][0-9]+)?$"));
        if (isNumeric) {
            m = Double.parseDouble(texto);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, conversor(m,d,o), "Resultado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Error, solo números", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        }else{
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Ingrese un valor", "Información", JOptionPane.WARNING_MESSAGE);
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversor_moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversor_moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversor_moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversor_moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversor_moneda().setVisible(true);
            }
        });
    }

    public String conversor(double m, String d, String o) {
        String res = "";
        switch (o) {
            case "Dólar":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 0.91));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 17.15));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libra Esterlina") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 0.78));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 7.78));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 142.12));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 1298.37));
                    res += " " + "Won sul-coreano";

                }
                break;
            case "Euros":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 1.10));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 18.82));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libras Esterlinas") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 0.85));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 8.54));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 155.96));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 1424.90));
                    res += " " + "Won sul-coreano";

                }
                break;
            case "Pesos Mexicanos":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 0.06));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 0.05));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libras Esterlinas") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 0.05));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 0.45));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 8.29));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 75.72));
                    res += " " + "Won sul-coreano";

                }
                break;
            case "Libra Esterlina":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 1.28));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 1.17));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 22.01));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libras Esterlinas") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 9.99));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 182.45));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 1667.29));
                    res += " " + "Won sul-coreano";

                }
                break;
            case "Quetzales":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 0.13));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 0.12));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 2.20));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libras Esterlinas") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 0.10));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 18.26));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 166.87));
                    res += " " + "Won sul-coreano";

                }
                break;
            case "Yen Japonés":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 0.01));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 0.01));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 0.12));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libras Esterlinas") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 0.01));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 0.05));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 9.14));
                    res += " " + "Won sul-coreano";

                }
                break;
            case "Won sul-coreano":
                if (d == "Dólar") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 0.00077002));
                    res += " " + "Dólares";
                } else if (d == "Euros") {
                    res += "Tienes €";
                    res += String.format("%,.2f", (m * 0.00070165));
                    res += " " + "Euros";
                } else if (d == "Pesos Mexicanos") {
                    res += "Tienes $";
                    res += String.format("%,.2f", (m * 0.01320369));
                    res += " " + "Pesos mexicanos";
                } else if (d == "Libras Esterlinas") {
                    res += "Tienes £";
                    res += String.format("%,.2f", (m * 0.00059978));
                    res += " " + "Libras esterlina";
                } else if (d == "Quetzales") {
                    res += "Tienes Q.";
                    res += String.format("%,.2f", (m * 0.00599255));
                    res += " " + "Quetzales";
                } else if (d == "Yen Japonés") {
                    res += "Tienes ¥";
                    res += String.format("%,.2f", (m * 0.10943203));
                    res += " " + "Yen japonés";
                } else if (d == "Won sul-coreano") {
                    res += "Tienes ₩";
                    res += String.format("%,.2f", (m * 1));
                    res += " " + "Won sul-coreano";

                }
                break;
            default:
                break;
        }

        return (res);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
